Install gprc-web on gen_proto

diff --git a/.github/workflows/_gen_proto.yaml b/.github/workflows/_gen_proto.yaml
--- a/.github/workflows/_gen_proto.yaml
+++ b/.github/workflows/_gen_proto.yaml
@@ -63,11 +63,12 @@ jobs:
 
       - name: Install proto generation tools
         run: |
-          npm install -g protoc-gen-js grpc-tools
+          npm install -g protoc-gen-js grpc-tools protoc-gen-grpc-web
           # Verify installations
           which protoc-gen-js || echo "protoc-gen-js not found in PATH"
           which grpc_tools_node_protoc_plugin || echo "grpc_tools_node_protoc_plugin not found in PATH"
           which grpc_tools_node_protoc_ts || echo "grpc_tools_node_protoc_ts not found in PATH"
+          which protoc-gen-grpc-web || echo "protoc-gen-grpc-web not found in PATH"
 
       - name: Generate ts from proto
         run: ${{ steps.setup-node.outputs.pm_run }} gen:proto
